modLoader = "javafml" #mandatory
loaderVersion = "56" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "MIT Licence" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
#clientSideOnly=true #optional
[[mods]] #mandatory
modId = "rockylib" #mandatory
version = "1.26.34+1.21.6" #mandatory
displayName = "RockyLib" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "icon.png" #optional
credits = "${credits}" #optional
authors = "RockyDev" #optional
description = '''A Library API For The Mods''' #mandatory (Supports multiline text)
[[dependencies.rockylib]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[56,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.rockylib]]
modId = "minecraft"
mandatory = true
versionRange = "1.21.6"
ordering = "NONE"
side = "BOTH"